FROM openfaas/of-watchdog:0.7.2 as watchdog
FROM node:12.13.0-alpine as ship

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

# Add non root user
RUN addgroup -S app && adduser app -S -G app
RUN chown app /home/app

WORKDIR /root/
# Turn down the verbosity to default level.
ENV NPM_CONFIG_LOGLEVEL warn

RUN mkdir -p /home/app

# Wrapper/boot-strapper
WORKDIR /home/app
COPY package*.json ./

# This ordering means the npm installation is cached for the outer function handler.
RUN npm i
# Copy all other source code to work directory
ADD . /home/app

# chmod for tmp is for a buildkit issue (@alexellis)
RUN chown app:app -R /home/app \
    && chmod 777 /tmp

USER app

ENV cgi_headers="true"
# SET ENTRYPOINT
ENV fprocess="node ./dist/index.js"
ENV mode="http"
# SET THE PORT HERE BELLOW
ENV upstream_url="http://127.0.0.1:3300"

ENV exec_timeout="60s"
ENV write_timeout="65s"
ENV read_timeout="65s"

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]